services:
  spring:
    image: bayudwiyansatria/spring-boot-boilerplate:latest
    build:
      context: .
      # Bug: https://github.com/orgs/community/discussions/26634
      args:
      - MAVEN_USERNAME=${MAVEN_USERNAME}
      - MAVEN_PASSWORD=${MAVEN_PASSWORD}
      #dockerfile: Dockerfile
      dockerfile: docker/ci.Dockerfile
    container_name: spring
    working_dir: /app
    networks:
    - app-network
    env_file:
    - .env
  nginx:
    image: bayudwiyansatria/nginx:spring
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    container_name: nginx
    working_dir: /usr/share/nginx/html
    ports:
    - "8080:80"
    depends_on:
    - spring
    networks:
    - app-network
volumes: {}
networks:
  app-network:
    driver: bridge
