name: Development
on:
  push:
    branches:
    - develop
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yml@master
    with:
      JAVA_VERSION: 21
      MAVEN_COMMAND: mvn --no-transfer-progress --file pom.xml --settings settings.xml clean package -DskipTests 
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yml@master
    with:
      JAVA_VERSION: 21
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}