name: Features
on:
  push:
    branches:
    - feature/**
  pull_request:
    branches:
    - master
    types:
    - opened
    - reopened
permissions:
  actions: read
  contents: read
  pull-requests: write
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yml@master
    with:
      JAVA_VERSION: 21
      MAVEN_COMMAND: mvn --no-transfer-progress --file pom.xml --settings settings.xml clean package -DskipTests 
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  test:
    name: Test
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yml@master
    with:
      JAVA_VERSION: 21
      MAVEN_COMMAND: mvn --no-transfer-progress --file pom.xml --settings settings.xml clean test verify
      ARTIFACT_NAME: coverage
      ARTIFACT_PATH: target/site/jacoco
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Code Quality
  #---------------------------------------------------------------------------------------------------------------------
  code-quality:
    name: Code Quality
    needs: 
    - test
    uses: bayudwiyansatria/.github/.github/workflows/code-analysis-codecov.yml@master
    with:
      ARTIFACT_NAME: coverage
      ARTIFACT_PATH: target/site/jacoco
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  #---------------------------------------------------------------------------------------------------------------------
  # Post Job
  #---------------------------------------------------------------------------------------------------------------------
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification to Slack
      uses: bayudwiyansatria/.github/actions/slack-webhook@master
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}