name: Main
on:
  push:
    branches:
    - master
permissions:
  contents: read
  pull-requests: write
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yml@master
    with:
      JAVA_VERSION: 21
      MAVEN_COMMAND: mvn --no-transfer-progress --file pom.xml --settings settings.xml clean package -DskipTests 
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  maven:
    name: Maven
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - 21
        os:
        - ubuntu-24.04
    outputs:
      version: ${{ steps.maven.outputs.version }}
    steps:
    - name: Prepare
      uses: actions/checkout@v3
    - name: Configure Java
      uses: bayudwiyansatria/.github/actions/configure-java@master
      with:
        java-version: ${{ matrix.java-version }}
        gpg-sign: false
    - name: Prepare Deployment
      id: maven
      run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  docker:
    name: Docker
    needs: 
    - build
    - maven
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: docker/ci.Dockerfile
      DOCKER_IMAGE_TAG: ${{ needs.maven.outputs.version }}
      DOCKER_BUILD_ARG: VERSION=${{ needs.maven.outputs.version }}
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: true
      ARTIFACT_NAME: target
      ARTIFACT_PATH: target
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    name: Deploy
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yml@master
    needs: 
    - build
    with:
      JAVA_VERSION: 21
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
