name: Release
on:
  workflow_dispatch:
    inputs:
      MAJOR_VERSION:
        type: number
        description: Major Version
        required: true
        default: 0
      MINOR_VERSION:
        type: number
        description: Minor Version
        required: true
        default: 0
      INCREMENTAL_VERSION:
        type: number
        description: Patch Version
        required: true
        default: 1
permissions:
  contents: read
  pull-requests: write
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-java-maven.yml@master
    with:
      JAVA_VERSION: 21
      MAVEN_COMMAND: mvn --no-transfer-progress --file pom.xml --settings settings.xml clean package -DskipTests 
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  docker:
    name: Docker
    needs: 
    - build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: docker/ci.Dockerfile
      DOCKER_IMAGE_TAG: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION}}
      DOCKER_BUILD_ARG: VERSION=${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION}}
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deploy
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yml@master
    needs:
    - build
    with:
      JAVA_VERSION: 21
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Publish
  #---------------------------------------------------------------------------------------------------------------------
  publish:
    name: Deploy
    uses: bayudwiyansatria/.github/.github/workflows/release-maven.yml@master
    needs:
    - build
    with:
      JAVA_VERSION: 21
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION }}
      INCREMENTAL_VERSION: ${{ inputs.INCREMENTAL_VERSION}}
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Release
    needs: 
    - publish
    uses: bayudwiyansatria/.github/.github/workflows/release-github.yml@master
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION }}
      INCREMENTAL_VERSION: ${{ inputs.INCREMENTAL_VERSION }}
      ARTIFACT_PACKAGES_TYPE: pom.xml
      ARTIFACT_ASSET: target
      ARTIFACT_NAME: target
      ARTIFACT_PATH: target
      COVERAGE_ENABLED: true
      COVERAGE_NAME: coverage
      COVERAGE_PATH: target/coverage
      DOCS_ENABLED: true
      DOCS_NAME: docs
      DOCS_PATH: target/docs
    secrets:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  #---------------------------------------------------------------------------------------------------------------------
  # GitHub Pages
  #---------------------------------------------------------------------------------------------------------------------
  pages:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.repository.visibility == 'public' }}
    name: GitHub Pages
    needs: 
    - release
    uses: bayudwiyansatria/.github/.github/workflows/release-github-pages.yml@master
    with:
      ARTIFACT_NAME: docs
      ARTIFACT_PATH: target/docs
      ARTIFACT_ROOT: target
    secrets:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
